version: '3'

services:
  plex:
    image: plexinc/pms-docker:latest
    network_mode: host
    environment:
      - PLEX_UID=${USER_ID}
      - PLEX_GID=${GROUP_ID}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./media/radarr/movies:/data/movies
      - ./media/sonarr/series:/data/tvshows
      - ./media/plex/config/:/config
    depends_on:
      - transmission
      - sonarr
      - radarr
    restart: always

  plexpy:
    image: linuxserver/plexpy:latest
    ports:
      - "8181:8181"
    networks:
      - web
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
    volumes:
      - ./media/plexpy:/config
      - ./media/plex/config/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs:ro
    depends_on:
      - plex
    restart: always

  transmission:
    image: linuxserver/transmission:latest
    networks:
      - web
    ports:
      - "9091:9091"
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./media/transmission/config/:/config
      - ./media/transmission/downloads/:/downloads
    restart: always

  sonarr:
    image: linuxserver/sonarr:latest
    networks:
      - web
    ports:
      - "8989:8989"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dev/rtc:/dev/rtc:ro
      - ./media/sonarr/series:/tv
      - ./media/sonarr/config:/config
      - ./media/transmission/downloads/:/downloads
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
    depends_on:
      - transmission
    restart: always

  radarr:
    image: linuxserver/radarr:latest
    networks:
      - web
    ports:
      - "7878:7878"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dev/rtc:/dev/rtc:ro
      - ./media/radarr/movies:/movies
      - ./media/radarr/config:/config
      - ./media/transmission/downloads/:/downloads
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
    depends_on:
      - transmission
    restart: always

  # Proxy to a bunch of public trackers
  jackett:
    image: linuxserver/jackett:latest
    networks:
      - web
    ports:
      - "9117:9117"
    volumes:
      - ./media/jackett/config/:/config
      - ./media/transmission/downloads/:/downloads
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
    restart: always

  cadvisor:
    image: google/cadvisor:latest
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk:/dev/disk:ro
    restart: always

  muximux:
    image: linuxserver/muximux
    ports:
      - "80:80"
    volumes:
      - ./media/muximux/config:/config
    restart: always

  duc:
    image: digitalman2112/duc
    ports:
      - "8888:80"
    volumes:
      - .:/data:ro
    restart: always

  watchtower:
    image: v2tec/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  static:
    image: nginx
    ports:
      - "8889:80"
    volumes:
      - ./static/:/usr/share/nginx/html:ro
    restart: always

networks:
  web:
