---
version: '3'

services:
  plex:
    container_name: wamc_plex
    image: plexinc/pms-docker:latest
    ports:
      - 32400:32400
    environment:
      - PLEX_UID=${USER_ID}
      - PLEX_GID=${GROUP_ID}
      - ADVERTISE_IP=http://${LOCAL_STATIC_IP}:32400,https://${DOMAIN_MAIN}:${PLEX_EXT_PORT}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/data
      - ./media/plex/config/:/config
      - ./media/plex/transcode/:/transcode
    labels:
      com.centurylinklabs.watchtower.enable: true
    devices:
      - /dev/dri:/dev/dri
    restart: always

  transmission:
    container_name: wamc_transmission
    image: ghcr.io/linuxserver/transmission:latest
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./media/transmission/config/:/config
      - ./data/torrents:/data/torrents
    labels:
      traefik.enable: true
      traefik.http.routers.transmission.rule: >-
        Host(`${DOMAIN_MAIN}`) && PathPrefix(`/transmission`)
      traefik.http.routers.transmission.tls.certresolver: acme-wamc
      com.centurylinklabs.watchtower.enable: true
    restart: always

  sonarr:
    container_name: wamc_sonarr
    image: ghcr.io/linuxserver/sonarr:latest
    labels:
      traefik.enable: true
      traefik.http.routers.sonarr.rule: >-
        Host(`${DOMAIN_MAIN}`) && PathPrefix(`/sonarr`)
      traefik.http.routers.sonarr.tls.certresolver: acme-wamc
      com.centurylinklabs.watchtower.enable: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dev/rtc:/dev/rtc:ro
      - ./media/sonarr/config:/config
      - ./data:/data
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
    restart: always

  bazarr:
    container_name: wamc_bazarr
    image: ghcr.io/linuxserver/bazarr:latest
    labels:
      traefik.enable: true
      traefik.http.routers.bazarr.rule: >-
        Host(`${DOMAIN_MAIN}`) && PathPrefix(`/bazarr`)
      traefik.http.routers.bazarr.tls.certresolver: acme-wamc
      com.centurylinklabs.watchtower.enable: true
    volumes:
      - ./media/bazarr/config:/config
      - ./data/media:/data/media
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
    restart: always

  radarr:
    container_name: wamc_radarr
    image: ghcr.io/linuxserver/radarr:latest
    labels:
      traefik.enable: true
      traefik.http.routers.radarr.rule: >-
        Host(`${DOMAIN_MAIN}`) && PathPrefix(`/radarr`)
      traefik.http.routers.radarr.tls.certresolver: acme-wamc
      com.centurylinklabs.watchtower.enable: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dev/rtc:/dev/rtc:ro
      - ./media/radarr/config:/config
      - ./data:/data
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
    restart: always

  # Proxy to a bunch of public trackers
  jackett:
    container_name: wamc_jackett
    image: ghcr.io/linuxserver/jackett:latest
    labels:
      traefik.enable: true
      traefik.http.routers.jackett.rule: >-
        Host(`${DOMAIN_MAIN}`) && PathPrefix(`/jackett`)
      traefik.http.routers.jackett.tls.certresolver: acme-wamc
      com.centurylinklabs.watchtower.enable: true
    volumes:
      - ./media/jackett/config/:/config
      - ./media/transmission/downloads/:/downloads
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
    restart: always

  webdu:
    container_name: wamc_webdu
    image: lutzky/webdu
    volumes:
      - .:/data:ro
    command:
      - "--base_path=/data"
    labels:
      traefik.enable: true
      traefik.http.routers.webdu.rule: >-
        Host(`${DOMAIN_MAIN}`) && PathPrefix(`/webdu`)
      traefik.http.routers.webdu.tls.certresolver: acme-wamc
      traefik.http.routers.webdu.middlewares: webdu-stripprefix
      traefik.http.middlewares.webdu-stripprefix.stripprefix.prefixes: /webdu
      com.centurylinklabs.watchtower.enable: true
    restart: always

  speedtest:
    container_name: wamc_speedtest
    image: e7db/speedtest
    ports:
      - "8082:80"
    restart: always

  scrutiny:
    container_name: scrutiny
    image: analogj/scrutiny
    restart: always
    ports:
      - "8083:8080"
    volumes:
      - /run/udev:/run/udev:ro
    cap_add:
      - SYS_RAWIO
    # Traefik not enabled: See https://github.com/AnalogJ/scrutiny/issues/56
    devices:
      - /dev/sda
      - /dev/sdb

  homer:
    container_name: wamc_homer
    image: b4bz/homer:latest
    restart: always
    environment:
      - UID=${USER_ID}
      - GID=${GROUP_ID}
    volumes:
      - ./homer/:/www/assets:ro
    labels:
      traefik.enable: true
      traefik.http.routers.homer.rule: >-
        Host(`${DOMAIN_MAIN}`) && PathPrefix(`/`)
      traefik.http.routers.homer.tls.certresolver: acme-wamc

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: always
    labels:
      com.centurylinklabs.watchtower.enable: true
    environment:
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_POLL_INTERVAL=60
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  traefik:
    image: traefik:v2.2
    restart: always
    ports:
      - "81:81"
      - "443:443"
      - "8080:8080"
    command:
      - --accesslog.filePath=/logs/access.log
      - --api.insecure=true
      - --global.sendanonymoususage=false
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web-https-redirector.address=:81
      - --entrypoints.web-https-redirector.http.redirections.entryPoint.to=web-secure
      - --entrypoints.web-https-redirector.http.redirections.entryPoint.scheme=https
      - --entrypoints.web-secure.http.middlewares=auth@docker
      - --entrypoints.web-secure.address=:443

      - --certificatesResolvers.acme-wamc.acme.email=lutzky@gmail.com
      - --certificatesResolvers.acme-wamc.acme.storage=/acme.json
      - --certificatesResolvers.acme-wamc.acme.httpChallenge.entryPoint=web-https-redirector
    labels:
      traefik.enable: true
      com.centurylinklabs.watchtower.enable: true
      traefik.http.middlewares.auth.basicauth.usersfile: /.htpasswd
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.htpasswd:/.htpasswd
      - ./acme.json:/acme.json
      - ./traefik-logs:/logs
    container_name: traefik
