version: '3'

services:
  plex:
    image: plexinc/pms-docker:latest
    network_mode: host
	container_name: plex
    environment:
      - PLEX_UID=${USER_ID}
      - PLEX_GID=${GROUP_ID}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/TV:/TV
      - /volume1/Movies:/Movies
      - /volume1/docker/plex/config/:/config
      - /volume1/docker/plex/transcode/:/transcode
    depends_on:
      - nzbget
      - transmission
      - sickgear
      - radarr
    restart: always

  tautulli:
    image: linuxserver/tautulli:latest
    networks:
      - web
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
    volumes:
      - /volume1/docker/tautulli:/config
      - /volume1/docker/plex/config/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs:ro
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=PathPrefix:/tautulli"
      - "traefik.port=8181"
    depends_on:
      - plex
    restart: always

  transmission:
    image: linuxserver/transmission:latest
    networks:
      - web
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/docker/transmission/config/:/config
      - /volume1/downloads/:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=PathPrefix:/transmission"
      - "traefik.port=9091"
    restart: always

  sickgear:
    image: deed02392/sickgear:latest
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=PathPrefix:/sickgear"
      - "traefik.port=8081"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/TV:/tv
      - /volume1/docker/sickgear/data:/data
      - /volume1/downloads/dst/TV/:/incoming
    environment:
      - APP_UID=${USER_ID}
      - APP_GID=${GROUP_ID}
    depends_on:
      - nzbget
	  - transmission
    restart: always

  radarr:
    image: linuxserver/radarr:latest
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=PathPrefix:/radarr"
      - "traefik.port=7878"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dev/rtc:/dev/rtc:ro
      - /volume1/Movies:/movies
      - /volume1/docker/radarr/config:/config
      - /volume1/downloads/:/downloads
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
    depends_on:
      - nzbget
	  - transmission
    restart: always

  # Proxy to a bunch of public trackers
  jackett:
    image: linuxserver/jackett:latest
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=PathPrefix:/jackett"
      - "traefik.port=9117"
    volumes:
      - ./media/jackett/config/:/config
      - ./media/transmission/downloads/:/downloads
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
    restart: always
    
  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    restart: always
    ports:
      - "6789:6789"
    networks:
      - web
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
    volumes:
      - ./media/nzbget/config:/config
      - ./media/nzbget/downloads:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.backend=nzbget"
      - "traefik.frontend.rule=Host:nzbget.${DOMAIN_NAME}"
      - "traefik.port=6789"
      - "traefik.docker.network=web"

  static:
    image: nginx
    networks:
      - web
    volumes:
      - ./static/:/usr/share/nginx/html:ro
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=PathPrefix:/"
    restart: always

  traefik:
    image: traefik
    restart: always
    ports:
      - "8111:80"
      - "8112:443"
      - "8113:8080"
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
      - ./.htpasswd:/.htpasswd
    container_name: traefik
  traefik_local:
    image: traefik
    restart: always
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik_local.toml:/traefik.toml
    container_name: traefik_local

networks:
  web:
